name:                waniStructureTEST
version:             1.0.0.1
git:                 https://github.com/hinarid/waniStructure
license:             BSD3
author:              Hinari Daido
maintainer:          Hinari Daido
copyright:           Hinari Daido

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/hinarid/waniTest>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.4
  - text >= 1.2
  - array >= 0.5.3.0
  - mtl >= 2.2.2
  - directory >=1.3.3.0
  - data-default
  - split
  - cmdargs
  - lightblue
  - time >= 1.9.3

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  exposed-modules:
  - StructureTest.BackwardRules.TestBase
  - StructureTest.BackwardRules.Membership
  - StructureTest.BackwardRules.PiIntro
  - StructureTest.BackwardRules.PiElim

executables:
  waniStructureTEST:
    source-dirs: app
    main: Main.hs
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: waniStructureTEST
