resolver: lts-15.1

flags: {}

extra-deps:
  - git: git@github.com:DaisukeBekki/JSeM.git
    commit: d5705b42006a08aa9dd8d2ea37d29fc7cf5559f6
  - git: git@github.com:DaisukeBekki/hasktorch-tools.git
    commit: 936928cdee27e179a5e3775d146046b107b0eba1
  - git: https://github.com/DaisukeBekki/lightblue.git
    commit: 43b95bc7d51317aa53743e78a09f5fde7969e920

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true